fun_ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portofolio.urls')),
    path('schedule/', include(('jadwal.urls', 'jadwal'), namespace='jadwal')),
]

jadwal/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.schedule_list,name='schedule_list'),
    path('add/', views.schedule, name='schedule'),
    path('activity/<int:activity_id>/delete/',views.schedule_delete,name='delete'),
    path('activity/<int:activity_id>/edit/',views.schedule_edit,name='edit'),
]

portofolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.portofolio, name='portofolio'),
    path('form/', views.form, name='form'),
]

jadwal/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    activity_detail = models.CharField(max_length=30)
    category = models.CharField(max_length = 30)
    place = models.CharField(max_length=30)
    day = models.CharField(max_length=10)
    date = models.DateField()
    time = models.TimeField()
    description = models.TextField()

    def __str__(self):
        return self.activity_detail

portofolio/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms
from django.conf.global_settings import DATE_INPUT_FORMATS

class ScheduleForm(forms.Form):
    activity_title=forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'validate','id':'nama_kegiatan', 'tag':'Nama Kegiatan'}))
    category = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'validate','id':'kategori','tag':'Kategori'}))
    place = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'validate','id':'tempat','tag':'Tempat'}))
    date = forms.DateField(widget=forms.DateInput(attrs={'id':'tanggal','class':'datepicker validate', 'tag':'Tanggal Kegiatan'}))
    time = forms.TimeField(widget=forms.TimeInput(format='%H:%M',attrs={'class':'timepicker validate','id':'jam', 'tag':'Jam'}))
    description = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'class':'materialize-textarea','id':'deskripsi','tag':'Deskripsi'}))

    # def __init__(self, activity_title, category, place,date,time,description):
    #     super().__init__()
    #     activity_title=forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'validate','id':'nama_kegiatan', 'tag':'Nama Kegiatan', 'value':activity_title}))
    #     category = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'validate','id':'kategori','tag':'Kategori', 'value':category}))
    #     place = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'validate','id':'tempat','tag':'Tempat','value':place}))
    #     date = forms.DateField(widget=forms.DateInput(attrs={'id':'tanggal','class':'datepicker validate', 'tag':'Tanggal Kegiatan', 'value':date}))
    #     time = forms.TimeField(widget=forms.TimeInput(format='%H:%M',attrs={'class':'timepicker validate','id':'jam', 'tag':'Jam', 'value':time}))
    #     description = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'class':'materialize-textarea','id':'deskripsi','tag':'Deskripsi', 'value':description}))

jadwal/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .forms import ScheduleForm
from .models import Schedule
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime


# Create your views here.

def schedule(request):
    if(request.method == "POST"):
        if(int(request.POST["id"])>=0):
            schedule_item = get_object_or_404(Schedule, id=request.POST["id"])
            dateArray = request.POST["date"].split("|")
            day = dateArray[0].strip()
            date = dateArray[1].strip()
            schedule_item.activity_detail = request.POST["activity_title"]
            schedule_item.category = request.POST["category"]
            schedule_item.place = request.POST["place"]
            schedule_item.day = day
            schedule_item.date = date
            schedule_item.time = request.POST["time"]
            schedule_item.description = request.POST["description"]
            schedule_item.save()
            return HttpResponseRedirect(reverse('jadwal:schedule_list'))
        else:
            data = request.POST
            dateArray = data["date"].split("|")
            day = dateArray[0].strip()
            date = dateArray[1].strip()
            sched_form = ScheduleForm(data)
            if(sched_form.is_valid):
                print(request.POST)
                new_schedule = Schedule()
                new_schedule.activity_detail = data["activity_title"]
                new_schedule.category = data["category"]
                new_schedule.place = data["place"]
                new_schedule.day = day
                new_schedule.date = date
                new_schedule.time = data["time"]
                new_schedule.description = data["description"]
                new_schedule.save()
                return HttpResponseRedirect(reverse('jadwal:schedule_list'))
            else:
                return HttpResponseRedirect(reverse('jadwal:schedule'))
    elif(request.method == "GET"):
        schedule_form = ScheduleForm()
        return render(request, "jadwal.html",{'form_jadwal':schedule_form,'activity_id':-1})



def schedule_list(request):
    if(request.method == "GET"):
        list_day = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
        activities = Schedule.objects.all()
        return render(request, "list_jadwal.html", {'list_day':list_day, 'list_activity':activities})
    else:
        return HttpResponseRedirect(reverse('jadwal:schedule_list'))

def schedule_delete(request, activity_id):
    schedule_item = Schedule.objects.get(id=int(activity_id))
    schedule_item.delete()
    return HttpResponseRedirect(reverse('jadwal:schedule_list'))

def schedule_edit(request, activity_id):

    schedule_item = get_object_or_404(Schedule, id=activity_id)
    day = schedule_item.day
    date = schedule_item.date.strftime("%Y-%m-%d")
    fulldate = day + " | " + date
    time = schedule_item.time.strftime("%H:%M")

    data = {'activity_title': schedule_item.activity_detail, 'category':schedule_item.category, 'place':schedule_item.place, 'date':fulldate, 'time':time, 'description':schedule_item.description}

    schedule_form = ScheduleForm(data)
    return render(request, "jadwal.html", {'form_jadwal':schedule_form,'activity_id':schedule_item.id})

portofolio/views.py
from django.shortcuts import render

# Create your views here.


def portofolio(request):
    return render(request, 'index.html')

def form(request):
    return render(request, 'form.html')

fun_ppw/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link
      type="text/css"
      rel="stylesheet"
      href="{% static './css/materialize.css' %}"
      media="screen,projection"
    />
    <link
      href="https://fonts.googleapis.com/css?family=B612|Roboto+Mono&display=swap"
      rel="stylesheet"
    />
    <link
      type="text/css"
      rel="stylesheet"
      href="{% static './css/style.css' %}"
    />
    <title>Zuhdi's Portofolio</title>
  </head>
  <body>
    <div id="navbar">
      {% block navbar %}{% endblock %}
    </div>

    <div id="content">
      {% block content %}{% endblock %}
    </div>

    <div id="footer">
      {% block footer %}{% endblock %}
    </div>
    <script src="{% static './js/materialize.js' %}"></script>
    <script src="{% static './js/script.js' %}"></script>
  </body>
</html>

fun_ppw/templates/navbar.html
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper grey darken-3">
      <!-- <a href="#" class="brand-logo">Z</a> -->
      <ul id="nav-mobile" class="center-align hide-on-small-only">
        <li><a href="{% url 'portofolio' %}">Home</a></li>
        <li><a href="{% url 'portofolio' %}#about">About Me</a></li>
        <li><a href="{% url 'portofolio' %}#skill">Skills</a></li>
        <li><a href="{% url 'portofolio' %}#project">Projects</a></li>
        <li><a href="{% url 'jadwal:schedule_list' %}">Schedule</a></li>
      </ul>
    </div>
  </nav>
</div>

jadwal/templates/jadwal.html
{% extends "base.html" %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<section class="section row jadwal">
    <h4>Schedule</h4>
    <form class="col m12" action="{% url 'jadwal:schedule' %}" method="post">
        {% csrf_token %}
        {% for field in form_jadwal %}
            <div class="input-field">
                {{ field }}
                {{ field.label_tag }}
            </div>
        {% endfor %}
        
        <input type="hidden" name="id" value="{{ activity_id }}">

        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
</section>
{% endblock %}

jadwal/templates/list_jadwal.html
{% extends "base.html" %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

{% block content %}
<div class="section row list-jadwal">
        <a href="{% url 'jadwal:schedule' %}" class="waves-effect waves-light btn">ADD ACTIVITY</a>
        <ul class="collapsible expandable">
                {% for day in list_day %}
                <li>
                    <div class="collapsible-header"><i class="material-icons">today</i>{{ day }}</div>
                    <div class="collapsible-body">
                        <div class="row">
                                {% for item in list_activity %}
                                {% if day == item.day %}
                                    <div class="col m4">
                                        <p class="judul">{{ item.activity_detail }}</p>
                                        <div class="row items">
                                            <div class="col m4">
                                                <i class="material-icons">
                                                category
                                                </i>
                                            </div>
                                            <div class="col m8">
                                                <p>
                                                    {{ item.category }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="row items">
                                            <div class="col m4">
                                                <i class="material-icons">
                                                map
                                                </i>
                                            </div>
                                            <div class="col m8">
                                                <p>

                                                    {{ item.place }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="row items">
                                            <div class="col m4">
                                                <i class="material-icons">
                                                calendar_today
                                                </i>
                                            </div>
                                            <div class="col m8">
                                                <p>

                                                    {{ item.day }}
                                                </p>
                                            </div>
                                        </div>
            
                                        <div class="row items">
                                            <div class="col m4">
                                                <i class="material-icons">
                                                date_range
                                                </i>
                                            </div>
                                            <div class="col m8">
                                                <p>
                                                    {{ item.date }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="row items">
                                            <div class="col m4">
                                                <i class="material-icons">
                                                access_time
                                                </i>
                                            </div>
                                            <div class="col m8">
                                                <p>
                                                    {{ item.time }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="row items">
                                            <div class="col m4">
                                                <i class="material-icons">
                                                description
                                                </i>
                                            </div>
                                            <div class="col m8">
                                                <p>
                                                    {{ item.description }}
                                                </p>
                                            </div>
                                        </div>
                                        <form class="col s6 delete" action="{% url 'jadwal:delete' item.id %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn-small waves-effect waves-light red accent-3" type="submit" name="action">Delete
                                                <i class="material-icons right">delete</i>
                                            </button>
                                        </form>
                                        <div class="edit col s6">
                                            <a class="btn-small waves-effect waves-light green accent-3" href="{% url 'jadwal:edit' item.id %}">Edit<i class="material-icons right">edit</i></a>
                                        </div>
                                    
                                    </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}

portofolio/templates/footer.html
{% load static %}
    <section class="row contact">
      <h4>Reach me on</h4>
      <div class="row contact-box">
        <div class="col m3 s6 contact-icon">
          <a href="https://www.linkedin.com/in/mzuhdi52/">
            <img src="{% static 'portofolio/src/linkedin.svg' %}" alt="LinkedIn" />
          </a>
        </div>
        <div class="col m3 s6 contact-icon">
          <a href="mailto:mzuhdi.zamrud@gmail.com">
            <img src="{% static 'portofolio/src/gmail.svg' %}" alt="GMail" />
          </a>
        </div>
        <div class="col m3 s6 contact-icon">
          <a href="https://github.com/KiddoKidz">
            <img src="{% static 'portofolio/src/github-sign.svg' %}" alt="Github" />
          </a>
        </div>
        <div class="col m3 s6 contact-icon">
          <a href="{% url 'form' %}">
            <img src="{% static 'portofolio/src/logo_feed.png' %}" alt="Feedback" />
          </a>
        </div>
      </div>
    </section>

portofolio/templates/form.html
{% extends 'base.html' %}
{% block navbar %} 
    {% include "navbar.html" %} 
{% endblock %}

{% block content %}
    <section class="section row forms">
      <h4>
        Feedback Form
      </h4>
      <form class="col s12">
        <div class="row">
          <div class="input-field col s6">
            <input id="first_name" type="text" class="validate" />
            <label for="first_name">First Name</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="email" type="email" class="validate" />
            <label for="email">Email</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <textarea id="textarea1" class="materialize-textarea"></textarea>
            <label for="textarea1">Textarea</label>
          </div>
        </div>
        <div class="row button-cont">
          <button class="btn waves-effect waves-light">Send</button>
        </div>
      </form>
    </section>

{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

portofolio/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block navbar %} 
    {% include "navbar.html" %} 
{% endblock %}

{% block content %}

<section class="section row profile" id="home">
  <div class="col desc">
    <h4>Hi, I'm Zuhdi</h4>
    <h5>JUNIOR WEB DEVELOPER</h5>
  </div>
  <div class="col photo">
    <img src="{% static 'portofolio/src/profpict.svg' %}" alt="Zuhdi" />
  </div>
</section>

<section class="row section about" id="about">
  <h4>About Me</h4>
  <div class="col isi black-text">
    <p>
      Hello, my name is Muhammad Zuhdi Zamrud. People usually calls me as Zuhdi.
      I’m 19 years old. Currently, I’m going to University of Indonesia. I’m
      majoring in Computer Science.
    </p>
  </div>
</section>

<div class="garis row"></div>

<section class="section row edex">
  <div class="col s12 m6 edu">
    <h4>Education</h4>
    <div class="logo-desc">
      <img class="hide-on-med-and-down" src="{% static 'portofolio/src/logo_ui.svg' %}" alt="UI" />
      <div class="desc">
        <h5>Universitas Indonesia</h5>
        <p>Computer Science</p>
      </div>
    </div>
  </div>
  <div class="col s12 m6 exp">
    <h4>Experience</h4>
    <div class="logo-desc">
      <img class="hide-on-med-and-down" src="{% static 'portofolio/src/logo_bem.svg' %}" alt="BEM" />
      <div class="desc">
        <h5>BEM Fasilkom UI</h5>
        <p>Staff of Business and Partnership</p>
      </div>
    </div>
    <div class="logo-desc">
      <img class="hide-on-med-and-down" src="{% static 'portofolio/src/logo_grit.svg' %}" alt="GRIT" />
      <div class="desc">
        <h5>PT GRIT</h5>
        <p>Mobile App Development Intern</p>
      </div>
    </div>
  </div>
</section>

<section class="section row skill" id="skill">
  <h4>
    Skills
  </h4>
  <div class="garis"></div>
  <div class="row skill-row odd-skill">
    <div class="col s12 m4 skill-logo">
      <img src="{% static 'portofolio/src/logo_css3.svg' %}" alt="CSS" />
    </div>
    <div class="col s12 m4 skill-logo">
      <img src="{% static 'portofolio/src/logo_java.svg' %}" alt="Java" />
    </div>
    <div class="col s12 m4 skill-logo">
      <img src="{% static 'portofolio/src/logo_python.svg' %}" alt="Python" />
    </div>
  </div>
  <div class="row skill-row even-skill">
    <div class="col s12 m6 skill-logo">
      <img src="{% static 'portofolio/src/logo_html.svg' %}" alt="CSS" />
    </div>
    <div class="col s12 m6 skill-logo">
      <img src="{% static 'portofolio/src/logo_js.svg' %}" alt="Java" />
    </div>
  </div>
</section>

<section class="section row project" id="project">
  <h4>Projects</h4>
  <div class="garis"></div>
  <div class="row">
    <div class="col s12 m4 card-piece">
      <div class="card">
        <div class="card-image">
          <img src="{% static 'portofolio/src/burgerbuilder.png' %}" />
          <span class="card-title">Burger Builder</span>
        </div>
        <div class="card-content">
          <p>
            My self project
          </p>
        </div>
      </div>
    </div>
    <div class="col s12 m4 card-piece">
      <div class="card">
        <div class="card-image">
          <img src="{% static 'portofolio/src/tpamakara.png' %}" />
          <span class="card-title">TPA Makara UI</span>
        </div>
        <div class="card-content">
          <p>
            Project from client
          </p>
        </div>
      </div>
    </div>
    <!-- <div class="col s12 m4 card-piece">
          <div class="card">
            <div class="card-image">
              <img src="src/burgerbuilder.png" />
              <span class="card-title">Burger Builder</span>
            </div>
            <div class="card-content">
              <p>
                My self project
              </p>
            </div>
          </div>
        </div> -->
  </div>
</section>
{% endblock %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}